=== taheri24/xpanel/specs/xfeature/feature-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <!-- Root Element -->
  <xs:element name="Feature">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Backend"/>
        <xs:element ref="Frontend"/>
        <xs:element ref="ParameterMapping" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Version" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <!-- ============================= -->
  <!-- BACKEND ELEMENTS              -->
  <!-- ============================= -->
  
  <xs:element name="Backend">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Query"/>
        <xs:element ref="ActionQuery"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Query">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="Id" type="xs:string" use="required"/>
          <xs:attribute name="Type" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Select"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="Description" type="xs:string" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="ActionQuery">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="Id" type="xs:string" use="required"/>
          <xs:attribute name="Type" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Insert"/>
                <xs:enumeration value="Update"/>
                <xs:enumeration value="Delete"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="Description" type="xs:string" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <!-- ============================= -->
  <!-- FRONTEND ELEMENTS             -->
  <!-- ============================= -->
  
  <xs:element name="Frontend">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Form"/>
        <xs:element ref="DataTable"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Form">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Field"/>
        <xs:element ref="Button"/>
        <xs:element ref="Message"/>
      </xs:choice>
      <xs:attribute name="Id" type="xs:string" use="required"/>
      <xs:attribute name="Mode" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Create"/>
            <xs:enumeration value="Edit"/>
            <xs:enumeration value="View"/>
            <xs:enumeration value="Delete"/>
            <xs:enumeration value="Search"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Dialog" type="xs:boolean" use="required"/>
      <xs:attribute name="Title" type="xs:string" use="required"/>
      <xs:attribute name="ActionRef" type="xs:string" use="optional"/>
      <xs:attribute name="QueryRef" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Field">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Option" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Label" type="xs:string" use="optional"/>
      <xs:attribute name="Type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Text"/>
            <xs:enumeration value="Email"/>
            <xs:enumeration value="Password"/>
            <xs:enumeration value="Tel"/>
            <xs:enumeration value="Number"/>
            <xs:enumeration value="Date"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="Time"/>
            <xs:enumeration value="Textarea"/>
            <xs:enumeration value="Select"/>
            <xs:enumeration value="Checkbox"/>
            <xs:enumeration value="Radio"/>
            <xs:enumeration value="Hidden"/>
            <xs:enumeration value="File"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Required" type="xs:boolean" use="optional" default="false"/>
      <xs:attribute name="Readonly" type="xs:boolean" use="optional" default="false"/>
      <xs:attribute name="Placeholder" type="xs:string" use="optional"/>
      <xs:attribute name="Validation" type="xs:string" use="optional"/>
      <xs:attribute name="Format" type="xs:string" use="optional"/>
      <xs:attribute name="DefaultValue" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Option">
    <xs:complexType>
      <xs:attribute name="Value" type="xs:string" use="required"/>
      <xs:attribute name="Label" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Button">
    <xs:complexType>
      <xs:attribute name="Type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Submit"/>
            <xs:enumeration value="Cancel"/>
            <xs:enumeration value="Reset"/>
            <xs:enumeration value="Close"/>
            <xs:enumeration value="Confirm"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Label" type="xs:string" use="required"/>
      <xs:attribute name="Style" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Primary"/>
            <xs:enumeration value="Secondary"/>
            <xs:enumeration value="Success"/>
            <xs:enumeration value="Danger"/>
            <xs:enumeration value="Warning"/>
            <xs:enumeration value="Info"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="ActionRef" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Message">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="Type" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Info"/>
                <xs:enumeration value="Success"/>
                <xs:enumeration value="Warning"/>
                <xs:enumeration value="Error"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="DataTable">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Column" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="Id" type="xs:string" use="required"/>
      <xs:attribute name="QueryRef" type="xs:string" use="required"/>
      <xs:attribute name="Title" type="xs:string" use="required"/>
      <xs:attribute name="Pagination" type="xs:boolean" use="optional" default="true"/>
      <xs:attribute name="PageSize" type="xs:positiveInteger" use="optional" default="20"/>
      <xs:attribute name="Sortable" type="xs:boolean" use="optional" default="true"/>
      <xs:attribute name="Filterable" type="xs:boolean" use="optional" default="false"/>
      <xs:attribute name="Searchable" type="xs:boolean" use="optional" default="false"/>
      <xs:attribute name="FormActions" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Column">
    <xs:complexType>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Label" type="xs:string" use="required"/>
      <xs:attribute name="Type" use="optional" default="Text">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Text"/>
            <xs:enumeration value="Number"/>
            <xs:enumeration value="Date"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Currency"/>
            <xs:enumeration value="Percentage"/>
            <xs:enumeration value="Link"/>
            <xs:enumeration value="Badge"/>
            <xs:enumeration value="Image"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Sortable" type="xs:boolean" use="optional" default="true"/>
      <xs:attribute name="Filterable" type="xs:boolean" use="optional" default="false"/>
      <xs:attribute name="Width" type="xs:string" use="optional"/>
      <xs:attribute name="Format" type="xs:string" use="optional"/>
      <xs:attribute name="Align" use="optional" default="Left">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Left"/>
            <xs:enumeration value="Center"/>
            <xs:enumeration value="Right"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="ParameterMapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ListQuery" minOccurs="0"/>
        <xs:element ref="Options" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="DataType" type="xs:string" use="required"/>
      <xs:attribute name="Label" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="ListQuery">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="Id" type="xs:string" use="required"/>
          <xs:attribute name="Type" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Select"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="Description" type="xs:string" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="Options">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Option" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== taheri24/xpanel/sage-app/x/SageLines.xml
<?xml version="1.0" encoding="UTF-8"?>
<Feature Name="SageLines" Version="1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="feature-schema.xsd">

  <!-- ============================= -->
  <!-- BACKEND ELEMENTS              -->
  <!-- ============================= -->
  <Backend>

    <!-- SELECT QUERIES: Data retrieval operations -->
    <Query Id="ListLineItems" Type="Select" Description="Retrieve all line items from Sage and Portal invoices">
      <![CDATA[
        SELECT
          ITMREF_0 collate Latin1_General_BIN ITMREF_0,
          ITMDES_0 collate Latin1_General_BIN ITMDES_0,
          QTYSTU_0,
          'Recipt_Sage' loc
        FROM [TR-EDOCS].[dbo].[sagedbLIVEPRECEIPTD]
        WHERE PTHNUM_0 = (
          SELECT PTHNUM_0
          FROM [TR-EDOCS].[dbo].[sagedbLIVEPRECEIPT]
          WHERE BPSNDE_0 = :invoiceNo
        )
        UNION ALL
        SELECT
          saticiUrunKodu,
          urunAdi,
          miktar,
          Recived_Invoice_Portal
        FROM [TR-EDOCS].[dbo].[PUR_INVD]
        WHERE belgeno = :invoiceNo
        ORDER BY 3, 4
      ]]>
    </Query>

    <Query Id="GetLineItemsByInvoice" Type="Select" Description="Retrieve line items for a specific invoice">
      <![CDATA[
        SELECT
          ITMREF_0 collate Latin1_General_BIN ITMREF_0,
          ITMDES_0 collate Latin1_General_BIN ITMDES_0,
          QTYSTU_0,
          'Recipt_Sage' loc
        FROM [TR-EDOCS].[dbo].[sagedbLIVEPRECEIPTD]
        WHERE PTHNUM_0 = (
          SELECT PTHNUM_0
          FROM [TR-EDOCS].[dbo].[sagedbLIVEPRECEIPT]
          WHERE BPSNDE_0 = :invoiceNo
        )
        UNION ALL
        SELECT
          saticiUrunKodu,
          urunAdi,
          miktar,
          Recived_Invoice_Portal
        FROM [TR-EDOCS].[dbo].[PUR_INVD]
        WHERE belgeno = :invoiceNo
        ORDER BY 3, 4
      ]]>
    </Query>

  </Backend>

  <!-- ============================= -->
  <!-- FRONTEND ELEMENTS             -->
  <!-- ============================= -->
  <Frontend>

    <!-- DATA TABLES: Display data in tabular format -->
    <DataTable Id="LineItemsTable" QueryRef="ListLineItems" Title="Invoice Line Items"
               Pagination="true" PageSize="25" Sortable="true" Searchable="true">
      <Column Name="ITMREF_0" Label="Product Code" Type="Text" Sortable="true" Width="150px"/>
      <Column Name="ITMDES_0" Label="Product Description" Type="Text" Sortable="true"/>
      <Column Name="QTYSTU_0" Label="Quantity" Type="Number" Sortable="true" Width="100px" Align="Right"/>
      <Column Name="loc" Label="Source" Type="Text" Sortable="true" Width="150px" Align="Center"/>
    </DataTable>

  </Frontend>

</Feature>

=== taheri24/xpanel/sage-app/x/SageInvoices.xml
<?xml version="1.0" encoding="UTF-8"?>
<Feature Name="SageInvoices" Version="1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="feature-schema.xsd">

  <!-- ============================= -->
  <!-- BACKEND ELEMENTS              -->
  <!-- ============================= -->
  <Backend>

    <!-- SELECT QUERIES: Data retrieval operations -->
    <Query Id="ListInvoices" Type="Select" Description="Retrieve all purchase invoices with tax and payment details" MockDataSet2="mock-invoices.json">
      <![CDATA[
       SELECT   [faturaNo]
      ,[faturaTarihi]
      ,[irsaliyeBilgisi_irsaliyeNo]
      ,[irsaliyeBilgisi_irsaliyeTarihi]
      ,[sonOdemeTarihi]
      ,[paraBirimi]
      ,[vergiler_toplamVergiTutari]
      ,[vergiHaricToplam]
      ,[faturaNot]
      ,[satici_vergiNo]
      ,[satici_unvan]
      ,[BP]
      ,[BP2]
  FROM [TR-EDOCS].[dbo].[TAB1]
 
       ORDER BY [faturaTarihi] DESC
             ]]>
    </Query>
   </Backend>

  <!-- ============================= -->
  <!-- FRONTEND ELEMENTS             -->
  <!-- ============================= -->
  <Frontend>

    <!-- DATA TABLES: Display data in tabular format -->
    <DataTable Id="InvoicesTable" QueryRef="ListInvoices" Title="Purchase Invoices"
               Pagination="true" PageSize="20" Sortable="true" Searchable="true">
      <Column Name="satici_vergiNo" Label="Vendor Tax ID" Type="Text" Sortable="true"/>
      <Column Name="faturaNo" Label="Invoice No" Type="Text" Sortable="true" Width="120px"/>
      <Column Name="faturaTarihi" Label="Invoice Date" Type="Date" Sortable="true" Width="120px"/>
      <Column Name="faturaTuru" Label="Invoice Type" Type="Text" Sortable="true"/>
      <Column Name="faturaTipi" Label="Invoice Category" Type="Text" Sortable="true"/>
      <Column Name="paraBirimi" Label="Currency" Type="Text" Sortable="true" Width="80px" Align="Center"/>
      <Column Name="Toplam" Label="Total Goods/Services" Type="Number" Sortable="true" Width="130px" Align="Right"/>
      <Column Name="vergi" Label="Tax Amount" Type="Number" Sortable="true" Width="120px" Align="Right"/>
      <Column Name="odenecekTutar" Label="Total Payable" Type="Number" Sortable="true" Width="130px" Align="Right"/>
    </DataTable>

  </Frontend>

</Feature>

=== taheri24/xpanel/sage-app/x/SageReceipt.xml
<?xml version="1.0" encoding="UTF-8"?>
<Feature Name="SageReceipt" Version="1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="feature-schema.xsd">

  <!-- ============================= -->
  <!-- BACKEND ELEMENTS              -->
  <!-- ============================= -->
  <Backend>

    <!-- SELECT QUERIES: Data retrieval operations -->
    <Query Id="ListReceipts" Type="Select" Description="Retrieve all Sage receipt records" MockFile2="mock-receipts.json">
      <![CDATA[
        SELECT
          PTHNUM_0,
          BPSNDE_0,
          @ref AS RCPDAT_0
        FROM [TR-EDOCS].[dbo].[sagedbLIVEPRECEIPTD]
        
       WHERE BPSNDE_0 = @ref 
        ORDER BY RCPDAT_0 DESC
      ]]>
    </Query>
   </Backend>

  <!-- ============================= -->
  <!-- FRONTEND ELEMENTS             -->
  <!-- ============================= -->
  <Frontend>

    <!-- DATA TABLES: Display data in tabular format -->
    <DataTable Id="ReceiptsTable" QueryRef="ListReceipts" Title="Sage Receipt Records"
               Pagination="true" PageSize="20" Sortable="true" Searchable="true">
      <Column Name="PTHNUM_0" Label="Receipt Number" Type="Text" Sortable="true" Width="150px"/>
      <Column Name="BPSNDE_0" Label="Invoice Number" Type="Text" Sortable="true" Width="150px"/>
      <Column Name="RCPDAT_0" Label="Receipt Date" Type="Date" Sortable="true" Width="130px"/>
    </DataTable>

  </Frontend>

</Feature>
